version: '3.8'
services:
  store-elasticsearch:
    container_name: store-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    #volumes:
    #  - ./volumes/jhipster/store/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'xpack.security.enabled=false'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
  store-mysql:
    image: mysql:8.0.30
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    #  - ./volumes/jhipster/store/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      #- MYSQL_ROOT_PASSWORD=passW0rd
      - MYSQL_DATABASE=store
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  elasticvue:
    image: cars10/elasticvue
    ports:
      - 8090:8080

  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://store-elasticsearch:9200
      - HQ_DEBUG=False
    ports:
      - 5000:5000

  phpmyadmin:
    depends_on:
      - store-mysql
    image: phpmyadmin
    restart: always
    ports:
      - '8010:80'
    environment:
      PMA_HOST: store-mysql
      PMA_PMADB: store
      PMA_USER: root
      #MYSQL_ROOT_PASSWORD: password
